apiVersion: v1
kind: Service
metadata:
 name: service-2
spec:
 selector:
   role: proxy-2
 ports:
   - protocol: TCP
     port: 80
     targetPort: 9000
 type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: service-2
 labels:
   role: proxy-2
spec:
 replicas: 1
 selector:
   matchLabels:
     role: proxy-2
 template:
   metadata:
     labels:
       role: proxy-2
   spec:
     containers:
     - name: proxy-2
       image: "saintlyzero/agni:dt-pxy"
       imagePullPolicy: Always
       env:
        - name: TRACE_SOURCE_ID
          value: service-2
     - name: ms-2
       image: "saintlyzero/agni:dt-srv-2"
       imagePullPolicy: Always
