apiVersion: v1
kind: Service
metadata:
 name: service-5
spec:
 selector:
   role: proxy-5
 ports:
   - protocol: TCP
     port: 80
     targetPort: 9000
 type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: service-5
 labels:
   role: proxy-5
spec:
 replicas: 1
 selector:
   matchLabels:
     role: proxy-5
 template:
   metadata:
     labels:
       role: proxy-5
   spec:
     containers:
     - name: proxy-5
       image: "saintlyzero/agni:dt-pxy"
       imagePullPolicy: Always
       env:
        - name: TRACE_SOURCE_ID
          value: service-5
     - name: ms-5
       image: "saintlyzero/agni:dt-srv-5"
       imagePullPolicy: Always
