apiVersion: v1
kind: Service
metadata:
 name: service-11
spec:
 selector:
   role: proxy-11
 ports:
   - protocol: TCP
     port: 80
     targetPort: 9000
 type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: service-11
 labels:
   role: proxy-11
spec:
 replicas: 1
 selector:
   matchLabels:
     role: proxy-11
 template:
   metadata:
     labels:
       role: proxy-11
   spec:
     containers:
     - name: proxy-11
       image: "saintlyzero/agni:dt-pxy"
       imagePullPolicy: Always
       env:
        - name: TRACE_SOURCE_ID
          value: service-11
     - name: ms-11
       image: "saintlyzero/agni:dt-srv-11"
       imagePullPolicy: Always
