apiVersion: v1
kind: Service
metadata:
 name: service-6
spec:
 selector:
   role: proxy-6
 ports:
   - protocol: TCP
     port: 80
     targetPort: 9000
 type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: service-6
 labels:
   role: proxy-6
spec:
 replicas: 1
 selector:
   matchLabels:
     role: proxy-6
 template:
   metadata:
     labels:
       role: proxy-6
   spec:
     containers:
     - name: proxy-6
       image: "saintlyzero/agni:dt-pxy"
       imagePullPolicy: Always
       env:
        - name: TRACE_SOURCE_ID
          value: service-6
     - name: ms-6
       image: "saintlyzero/agni:dt-srv-6"
       imagePullPolicy: Always
