apiVersion: v1
kind: Service
metadata:
 name: v-backend
spec:
 selector:
   role: v-backend
 ports:
   - protocol: TCP
     port: 80
     targetPort: 9000
 type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: v-backend
 labels:
   role: v-backend
spec:
 replicas: 1
 selector:
   matchLabels:
     role: v-backend
 template:
   metadata:
     labels:
       role: v-backend
   spec:
     containers:
     - name: v-backend
       image: "saintlyzero/agni:dt-vb"
       imagePullPolicy: Always