apiVersion: v1
kind: Service
metadata:
 name: service-9
spec:
 selector:
   role: proxy-9
 ports:
   - protocol: TCP
     port: 80
     targetPort: 9000
 type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: service-9
 labels:
   role: proxy-9
spec:
 replicas: 1
 selector:
   matchLabels:
     role: proxy-9
 template:
   metadata:
     labels:
       role: proxy-9
   spec:
     containers:
     - name: proxy-9
       image: "saintlyzero/agni:dt-pxy"
       imagePullPolicy: Always
       env:
        - name: TRACE_SOURCE_ID
          value: service-9
     - name: ms-9
       image: "saintlyzero/agni:dt-srv-9"
       imagePullPolicy: Always
