apiVersion: v1
kind: Service
metadata:
 name: service-7
spec:
 selector:
   role: proxy-7
 ports:
   - protocol: TCP
     port: 80
     targetPort: 9000
 type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: service-7
 labels:
   role: proxy-7
spec:
 replicas: 1
 selector:
   matchLabels:
     role: proxy-7
 template:
   metadata:
     labels:
       role: proxy-7
   spec:
     containers:
     - name: proxy-7
       image: "saintlyzero/agni:dt-pxy"
       imagePullPolicy: Always
       env:
        - name: TRACE_SOURCE_ID
          value: service-7
     - name: ms-7
       image: "saintlyzero/agni:dt-srv-7"
       imagePullPolicy: Always
