apiVersion: v1
kind: Service
metadata:
 name: service-10
spec:
 selector:
   role: proxy-10
 ports:
   - protocol: TCP
     port: 80
     targetPort: 9000
 type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: service-10
 labels:
   role: proxy-10
spec:
 replicas: 1
 selector:
   matchLabels:
     role: proxy-10
 template:
   metadata:
     labels:
       role: proxy-10
   spec:
     containers:
     - name: proxy-10
       image: "saintlyzero/agni:dt-pxy"
       imagePullPolicy: Always
       env:
        - name: TRACE_SOURCE_ID
          value: service-10
     - name: ms-10
       image: "saintlyzero/agni:dt-srv-10"
       imagePullPolicy: Always
