apiVersion: v1
kind: Service
metadata:
 name: v-frontend
spec:
 selector:
   role: v-frontend
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80
 type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: v-frontend
 labels:
   role: v-frontend
spec:
 replicas: 1
 selector:
   matchLabels:
     role: v-frontend
 template:
   metadata:
     labels:
       role: v-frontend
   spec:
     containers:
     - name: v-frontend
       image: "saintlyzero/agni:dt-vf"
       imagePullPolicy: Always