apiVersion: v1
kind: Service
metadata:
 name: dt-svc
spec:
 selector:
   role: app
 ports:
   - protocol: TCP
     port: 9000
     targetPort: 9000
     nodePort: 32001
 type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: dt-deployment
 labels:
   role: app
spec:
 replicas: 1
 selector:
   matchLabels:
     role: app
 template:
   metadata:
     labels:
       role: app
   spec:
     containers:
     - name: app
       image: "docker.io/library/dt-pxy:latest"
     - name: web
       image: "docker.io/library/dt-srv:latest"
