apiVersion: v1
kind: Service
metadata:
 name: svc-dt-c
spec:
 selector:
   role: app
 ports:
   - protocol: TCP
     port: 9001
     targetPort: 9001
     nodePort: 32002
 type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployment-c
 labels:
   role: app
spec:
 replicas: 1
 selector:
   matchLabels:
     role: app
 template:
   metadata:
     labels:
       role: app
   spec:
     containers:
     - name: collector
       image: "saintlyzero/agni:dt-c"
