apiVersion: v1
kind: Service
metadata:
 name: collector
spec:
 selector:
   role: collector
 ports:
   - protocol: TCP
     port: 80
     targetPort: 9001
 type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: collector
 labels:
   role: collector
spec:
 replicas: 1
 selector:
   matchLabels:
     role: collector
 template:
   metadata:
     labels:
       role: collector
   spec:
     containers:
     - name: collector
       image: "saintlyzero/agni:dt-c"
       imagePullPolicy: Always